version: '2'

services:
  app_server:
    build: dev-ops/docker/containers/php7
    links:
      - app_mysql:mysql
    volumes_from:
      - app_sw_docker_volumes
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir

  app_mysql:
    build: dev-ops/docker/containers/mysql
    volumes_from:
      - app_volumes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  app_es:
    build: dev-ops/docker/containers/elastic-search

  app_volumes:
    image: tianon/true
    volumes:
      - .:/project
      - .:/var/www/shopware
