version: '3'

services:
  app_server:
    image: shopwarecoach/server
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir:Z
      - .:/var/www/shopware:delegated
      - ./php.ini:/usr/local/etc/php/php.ini
    links:
      - app_mysql:mysql
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir
      XDEBUG_CONFIG: idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost

    ports:
      - "80:80"

  app_mysql:
    image: shopwarecoach/mysql
    volumes:
      - ./dev-ops/docker/_volumes/app-mysql-data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: shopware
      TZ: Europe/Berlin
