version: '2'

services:
  app_server:
    build: dev-ops/docker/containers/php7
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir:Z
      - .:/var/www/shopware:delegated
    links:
      - app_mysql:mysql
    environment:
      TERM: xterm
      COMPOSER_CACHE_DIR: /var/www/composer-cache-dir
    ports:
      - "80:80"

  app_mysql:
    build: dev-ops/docker/containers/mysql
    volumes:
      - ./dev-ops/docker/_volumes/app-mysql-data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
