#override defaults for dev
version: "2"

services:
  app_server:
    ports:
      - "8083:80"
    volumes:
      - ~/.composer/cache:/var/www/composer-cache-dir
    networks:
      sw_docker:
        ipv4_address: 10.100.111.46

  app_mysql:
    networks:
      sw_docker:
        ipv4_address: 10.100.111.47

  app_es:
      networks:
        sw_docker:
          ipv4_address: 10.100.111.48

  app_sw_docker_volumes:
    image: tianon/true
    container_name: app_sw_docker_volumes
    volumes:
      - .:/project
      - .:/var/www/shopware
      - ./dev-ops/docker/_volumes/app-mysqldata:/var/lib/mysql

networks:
  sw_docker:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.100.111.0/24
        gateway: 10.100.111.1